name: build

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master
    # tags:
  pull_request:

jobs:
  build-images:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: build amnezia-wg-docker image without pushing (only outside master)
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          docker buildx build \
              --platform linux/arm/v7,linux/amd64,linux/amd64/v2,linux/amd64/v3 .
              
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: build amnezia-wg-docker image for ghcr.io
        if: ${{ github.ref == 'refs/heads/master' }}
        # env:
        #   GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   USERNAME: ${{ github.actor }}
        
        # better to use official login-action@v3 
        # echo ${GITHUB_PACKAGE_TOKEN} | docker login ghcr.io -u ${USERNAME} --password-stdin
        run: |
          docker buildx build --push \
              --platform linux/arm/v7 \
              -t ghcr.io/sergh-one/amnezia-wg-docker:latest .
